version: '2'

services:
 
  # Add drupal contener.
  drupal:
    image: "${IMAGE}"
    container_name: "${PROJECT_NAME}-drupal"
    restart: always
    ports:
        - "8888:80"
    volumes:
      - ./drupal/modules:/var/www/html/modules
      - ./drupal/profiles:/var/www/html/profiles
      - ./drupal/themes:/var/www/html/themes
    links:
      - mysql
  
  # Add MariaDB contener.
  mysql:
    image: mariadb
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --init-connect='SET NAMES UTF8;'
    container_name: "${PROJECT_NAME}-mariadb"
    restart: always
    volumes:
      - ./mariadb/date:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=drupal
    ports:
      - 3306:3306

  # Add Adminer contener.
  adminer:
    image: clue/adminer
    container_name: "${PROJECT_NAME}-adminer"
    ports:
      - 8081:80
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=1234
    links:
      - mysql

  # Add PHPMyAdmin contener.
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "${PROJECT_NAME}-phpmyadmin"
    links:
      - mysql
    ports:
      - 8082:80
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=1234
      - PMA_HOST=mysql
